# fly.toml app configuration file generated for delirium-assessment-tool on 2024-10-11T18:23:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'delirium-assessment-tool'
primary_region = 'bos'

[build]

[deploy]
  release_command = 'npx prisma reset'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
